# Generated by Django 5.0.7 on 2024-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
