# Generated by Django 5.0.7 on 2024-10-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='avg_buy',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='current_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='invested',
            field=models.BigIntegerField(null=True),
        ),
    ]
