# Generated by Django 5.0.7 on 2024-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stockholding_avg_buy_stockholding_current_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='avg_buy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='current_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='invested',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
